import { createGunzip } from "node:zlib";
import { Readable } from "node:stream";
import { NextResponse } from "next/server";
import { mapMeasurementSites, parseRawMeasurementSites, parseRoadMetringPoints, type RawMeasurementSite, type RoadMetringPoint } from "@/lib/ndw";
import { findImnRange, parseImnRoadRanges, parseVanEijckRayonCodes } from "@/lib/rayons";
export const dynamic="force-dynamic";export const runtime="nodejs";
const B={minLat:51.15,minLng:4.20,maxLat:52.30,maxLng:6.55};
async function streamSites(){const r=await fetch("https://opendata.ndw.nu/measurement_current.xml.gz",{cache:"no-store",headers:{"user-agent":"StandbyRadar-snapshot/0.6"}});if(!r.ok||!r.body)throw new Error(`NDW ${r.status}`);const stream=Readable.fromWeb(r.body as never).pipe(createGunzip()),decoder=new TextDecoder(),raw:RawMeasurementSite[]=[];let buffer="";const startRx=/<(?:(?:[A-Za-z0-9_-]+):)?measurementSiteRecord\b/i,endRx=/<\/(?:(?:[A-Za-z0-9_-]+):)?measurementSiteRecord>/i;for await(const chunk of stream){buffer+=decoder.decode(chunk as Uint8Array,{stream:true});while(true){const s=startRx.exec(buffer);if(!s){if(buffer.length>4096)buffer=buffer.slice(-4096);break;}const start=s.index,rest=buffer.slice(start),e=endRx.exec(rest);if(!e){buffer=rest;break;}const end=start+e.index+e[0].length;raw.push(...parseRawMeasurementSites(buffer.slice(start,end)));buffer=buffer.slice(end);}}return raw;}
async function roadPoints(){const all:RoadMetringPoint[]=[];let offset=0;for(let page=0;page<30;page++){const p=new URLSearchParams({where:"a_n_nr LIKE 'A%'",outFields:"a_n_nr,l_r,hectometer,hectomtrng",returnGeometry:"true",geometry:`${B.minLng},${B.minLat},${B.maxLng},${B.maxLat}`,geometryType:"esriGeometryEnvelope",inSR:"4326",spatialRel:"esriSpatialRelIntersects",outSR:"4326",resultOffset:String(offset),resultRecordCount:"2000",f:"geojson"}),r=await fetch(`https://geo.rijkswaterstaat.nl/arcgis/rest/services/GDR/nwb_metrering/MapServer/2/query?${p}`,{cache:"no-store"});if(!r.ok)throw new Error(`RWS ${r.status}`);const j=await r.json()as{features?:unknown[]};all.push(...parseRoadMetringPoints(j));const n=j.features?.length??0;if(n<2000)break;offset+=n;}return all;}
export async function GET(){const[raw,points,contracts,rayons]=await Promise.all([streamSites(),roadPoints(),fetch("https://stichtingimn.nl/gecontracteerde-bergers-2023-2026.php",{cache:"no-store"}).then(r=>r.text()),fetch("https://www.stichtingimn.nl/rayons.php",{cache:"no-store"}).then(r=>r.text())]);const codes=parseVanEijckRayonCodes(contracts),ranges=parseImnRoadRanges(rayons,codes),mapped=mapMeasurementSites(raw,points),sites=mapped.flatMap(site=>{const range=findImnRange(site.road,site.km,site.direction,ranges)??ranges.find(x=>x.road===site.road&&site.km>=x.fromKm&&site.km<=x.toKm);return range?[{id:site.id,name:site.name,lat:site.lat,lng:site.lng,road:site.road,km:site.km,direction:site.direction,mappingDistanceMeters:site.mappingDistanceMeters,rayon:range.rayon,rangeFromKm:range.fromKm,rangeToKm:range.toKm,speedIndexes:[...site.speedIndexes],flowIndexes:[...site.flowIndexes]}]:[];});return NextResponse.json({generatedAt:new Date().toISOString(),codes,ranges,rawCount:raw.length,mappedCount:mapped.length,scopedCount:sites.length,sites},{headers:{"Cache-Control":"no-store"}});}
