import { gunzipSync } from "node:zlib";
import { NextResponse } from "next/server";
import type { SourceStatus, StandbyAdvice, WeatherSnapshot } from "@/lib/types";
import { matrixSummary, parseEvents, parseMatrix, parseMeasurementSites, parseTrafficSamples, stripTags, tagValue } from "@/lib/ndw";
import { OPERATOR_LOCATIONS, buildSegments, findStandby, parseRwsRestAreas, segmentEvents, segmentMatrix, sensorMetrics, weatherScore } from "@/lib/engine";

export const dynamic="force-dynamic"; export const runtime="nodejs";
const URLS={current:"https://opendata.ndw.nu/actueel_beeld.xml.gz",matrix:"https://opendata.ndw.nu/Matrixsignaalinformatie.xml.gz",traffic:"https://opendata.ndw.nu/trafficspeed.xml.gz",sites:"https://opendata.ndw.nu/measurement_current.xml.gz",rws:"https://geo.rijkswaterstaat.nl/services/ogc/gdr/omgevingswet/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=wegen_verzorgingsplaatsen_beperkingengebied_rijk&outputFormat=application%2Fjson&srsName=EPSG%3A4326",weather:"https://api.open-meteo.com/v1/forecast"};
const fetchText=async(url:string,revalidate:number)=>{const r=await fetch(url,{next:{revalidate},headers:{"user-agent":"StandbyRadar/0.3"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=Buffer.from(await r.arrayBuffer()),text=b[0]===31&&b[1]===139?gunzipSync(b).toString("utf8"):b.toString("utf8");return{text,updatedAt:r.headers.get("last-modified")??r.headers.get("date")};};
const rushHour=()=>{const h=Number(new Intl.DateTimeFormat("nl-NL",{timeZone:"Europe/Amsterdam",hour:"2-digit",hour12:false}).format(new Date()));return(h>=6&&h<10)||(h>=15&&h<19);};
async function weatherMap(locations:typeof OPERATOR_LOCATIONS){if(!locations.length)return new Map<string,WeatherSnapshot>();const u=locations.filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(0,50),p=new URLSearchParams({latitude:u.map(x=>x.lat).join(","),longitude:u.map(x=>x.lng).join(","),current:"precipitation,wind_gusts_10m,visibility,weather_code",timezone:"Europe/Amsterdam"}),r=await fetch(`${URLS.weather}?${p}`,{next:{revalidate:300}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const raw=await r.json()as unknown,items=Array.isArray(raw)?raw:[raw],map=new Map<string,WeatherSnapshot>();u.forEach((l,i)=>{const c=(items[i]as{current?:Record<string,unknown>}|undefined)?.current??{};map.set(l.id,{precipitation:Number(c.precipitation??0),windGusts:Number(c.wind_gusts_10m??0),visibility:Number(c.visibility??0),weatherCode:c.weather_code===undefined?null:Number(c.weather_code),observedAt:typeof c.time==="string"?c.time:null});});return map;}

export async function GET(){
 const generatedAt=new Date().toISOString(); let sites=parseMeasurementSites(""),events=parseEvents(""),matrix=parseMatrix(""),samples=parseTrafficSamples("",new Map()),rwsAreas=OPERATOR_LOCATIONS.slice(0,0),weather=new Map<string,WeatherSnapshot>();
 const sources:SourceStatus[]=[
  {id:"ndw-sites",name:"NDW meetlocaties",ok:false,updatedAt:null,error:null,lineage:"NDW/RWS fysieke detectoren"},{id:"ndw-flow",name:"NDW snelheid + intensiteit",ok:false,updatedAt:null,error:null,lineage:"NDW/RWS fysieke detectoren"},{id:"rws-matrix",name:"RWS matrixsignalen",ok:false,updatedAt:null,error:null,lineage:"RWS wegkantsystemen via NDW"},{id:"ndw-current",name:"NDW Actueel Beeld",ok:false,updatedAt:null,error:null,lineage:"NDW leveranciers/situatieberichten"},{id:"rws-locations",name:"RWS verzorgingsplaatsen",ok:false,updatedAt:null,error:null,lineage:"Rijkswaterstaat GeoData"},{id:"weather",name:"Open-Meteo weer",ok:false,updatedAt:null,error:null,lineage:"Open-Meteo"}
 ];
 try{const x=await fetchText(URLS.sites,21600);sites=parseMeasurementSites(x.text);sources[0]={...sources[0],ok:sites.length>0,updatedAt:x.updatedAt,error:sites.length?null:"Geen bruikbare meetlocaties"};}catch(e){sources[0].error=e instanceof Error?e.message:"Niet bereikbaar";}
 const siteMap=new Map(sites.map(x=>[x.id,x]));
 await Promise.all([
  fetchText(URLS.traffic,20).then(x=>{samples=parseTrafficSamples(x.text,siteMap);sources[1]={...sources[1],ok:samples.length>0,updatedAt:x.updatedAt,error:samples.length?null:"Geen verse detectorwaarden"};}).catch(e=>{sources[1].error=e instanceof Error?e.message:"Niet bereikbaar";}),
  fetchText(URLS.matrix,20).then(x=>{matrix=parseMatrix(x.text);sources[2]={...sources[2],ok:true,updatedAt:x.updatedAt};}).catch(e=>{sources[2].error=e instanceof Error?e.message:"Niet bereikbaar";}),
  fetchText(URLS.current,20).then(x=>{events=parseEvents(x.text);sources[3]={...sources[3],ok:true,updatedAt:x.updatedAt??(stripTags(tagValue(x.text,"publicationTime")??"")||null)};}).catch(e=>{sources[3].error=e instanceof Error?e.message:"Niet bereikbaar";}),
  sites.length?fetchText(URLS.rws,21600).then(x=>{rwsAreas=parseRwsRestAreas(x.text,sites);sources[4]={...sources[4],ok:rwsAreas.length>0,updatedAt:x.updatedAt,error:rwsAreas.length?null:"Geen verzorgingsplaatsen gekoppeld"};}).catch(e=>{sources[4].error=e instanceof Error?e.message:"Niet bereikbaar";}):Promise.resolve()
 ]);
 const candidates=[...OPERATOR_LOCATIONS,...rwsAreas]; try{weather=await weatherMap(candidates);sources[5]={...sources[5],ok:weather.size>0,updatedAt:[...weather.values()][0]?.observedAt??generatedAt};}catch(e){sources[5].error=e instanceof Error?e.message:"Niet bereikbaar";}
 const sampleMap=new Map(samples.map(x=>[x.siteId,x])),segments=buildSegments(sites),advice:StandbyAdvice[]=[];
 for(const seg of segments){const match=findStandby(seg,candidates);if(!match)continue;const sensor=sensorMetrics(seg,sampleMap),msi=segmentMatrix(matrix,seg),inc=segmentEvents(seg,events),w=weather.get(match.location.id)??null,wp=weatherScore(w),corroboratingSignals=[sensor.sensorCount>0&&sensor.congestionIndex>=25,msi.clusters>0,inc.items.length>0,wp>=2].filter(Boolean).length;let score=Math.round(sensor.score+msi.score+inc.score+wp+(corroboratingSignals>=2?4:0));if(!sensor.sensorCount)score=Math.min(score,58);if(corroboratingSignals<=1)score=Math.min(score,54);score=Math.max(0,Math.min(96,score));const confidence:StandbyAdvice["confidence"]=sensor.sensorCount>=2&&corroboratingSignals>=2&&sources[1].ok&&sources[2].ok?"hoog":sensor.sensorCount>=1&&corroboratingSignals>=1?"middel":"laag",pressure:StandbyAdvice["pressure"]=score>=65?"hoog":score>=38?"verhoogd":"rustig",reasons=[`${seg.road} km ${seg.kmFrom}–${seg.kmTo} wordt als afzonderlijk 5-km-deel beoordeeld`,sensor.sensorCount?`${sensor.sensorCount} verse fysieke meetlocatie(s): mediaan ${sensor.averageSpeedKph??"—"} km/u${sensor.flowVehiclesPerHour!==null?`, circa ${sensor.flowVehiclesPerHour} voertuigen/uur per meetrichting`:""}`:"geen verse fysieke snelheid/intensiteit beschikbaar — score is daarom begrensd",msi.clusters?`${msi.clusters} lokale matrixcluster(s) binnen exact dit hectometerbereik`:"geen actieve matrixmaatregelen binnen dit hectometerbereik",inc.accidents?`${inc.accidents} actueel ongeval(len) ruimtelijk bij dit segment`:null,inc.obstructions?`${inc.obstructions} actuele blokkade(s)/obstakels ruimtelijk bij dit segment`:null,corroboratingSignals>=2?`${corroboratingSignals} verschillende signalen bevestigen verhoogde druk`:"onvoldoende bronbevestiging voor een hoge score",match.location.knownOperationalLocation?"stand-byplek is operationeel bekend":"stand-byplek is een officiële RWS-verzorgingsplaats; operationele geschiktheid nog te valideren"].filter((x):x is string=>Boolean(x));advice.push({id:`${seg.road}-${seg.kmFrom}-${seg.kmTo}`,road:seg.road,segmentName:`${seg.road} km ${seg.kmFrom}–${seg.kmTo}`,kmFrom:seg.kmFrom,kmTo:seg.kmTo,score,pressure,confidence,recommendedUnits:score>=72&&confidence!=="laag"?2:score>=38?1:0,sensorCount:sensor.sensorCount,averageSpeedKph:sensor.averageSpeedKph,flowVehiclesPerHour:sensor.flowVehiclesPerHour,congestionIndex:sensor.congestionIndex,localEvents:inc.items.length,accidents:inc.accidents,obstructions:inc.obstructions,matrixClusters:msi.clusters,lowSpeedMatrixClusters:msi.lowSpeed,corroboratingSignals,reasons,weather:w,standby:{id:match.location.id,name:match.location.name,address:match.location.address,lat:match.location.lat,lng:match.location.lng,kind:match.location.kind,knownOperationalLocation:match.location.knownOperationalLocation}});}
 advice.sort((a,b)=>b.score-a.score||b.corroboratingSignals-a.corroboratingSignals||a.road.localeCompare(b.road,"nl",{numeric:true})||a.kmFrom-b.kmFrom);const byRoad=matrixSummary(matrix),activeSignals=byRoad.reduce((n,x)=>n+x.active,0);
 return NextResponse.json({generatedAt,refreshAfterSeconds:30,region:"Noord-Brabant + Gelderland",events,advice,sources,matrix:{activeSignals,byRoad},meta:{eventCount:events.length,accidentCount:events.filter(x=>x.kind==="accident").length,obstructionCount:events.filter(x=>x.kind==="obstruction").length,trafficCount:events.filter(x=>x.kind==="traffic").length,closureCount:events.filter(x=>x.kind==="closure").length,segmentCount:segments.length,measuredSiteCount:samples.length,rushHour:rushHour(),modelVersion:"0.3-fusion-5km",note:"Elke snelweg wordt in vaste 5-km-segmenten beoordeeld. Fysieke snelheid/intensiteit is primair; lokale matrixsignalen en incidenten bevestigen de score. Zonder bronbevestiging wordt een hoge score automatisch begrensd. Alleen bekende operationele locaties en officiële RWS-verzorgingsplaatsen worden als stand-byplek gebruikt."}},{headers:{"Cache-Control":"no-store, max-age=0"}});
}