import type { StandbyLocation, TrafficEvent, WeatherSnapshot } from "@/lib/types";
import type { MatrixSignal, MeasurementSite, RoadMetringPoint, SiteTraffic } from "@/lib/ndw";
import { isActiveMatrix } from "@/lib/ndw";

export const SEGMENT_LENGTH_KM=5,MAX_EVENT_DISTANCE_KM=4.5,MAX_STANDBY_ROAD_DISTANCE_KM=8;
export type CandidateLocation=StandbyLocation&{road:string;accessKm:number;source:"operator"|"rws"};
export type Segment={road:string;kmFrom:number;kmTo:number;centerKm:number;lat:number;lng:number;sites:MeasurementSite[]};
export const OPERATOR_LOCATIONS:CandidateLocation[]=[
{id:"gouden-leeuw-zevenbergschen-hoek",name:"De Gouden Leeuw",address:"Moerdijkseweg 1, 4765 SJ Zevenbergschen Hoek",lat:51.685051,lng:4.656334,kind:"restaurant",knownOperationalLocation:true,road:"A16",accessKm:49,source:"operator"},
{id:"wouwse-tol-noord",name:"Wouwse Tol Noord",address:"Rijksweg 11, 4623 RM Bergen op Zoom",lat:51.505325,lng:4.349858,kind:"service_area",knownOperationalLocation:true,road:"A58",accessKm:101,source:"operator"},
{id:"mcdonalds-beuningen",name:"McDonald's Beuningen",address:"Hadrianussingel 37, 6642 AH Beuningen",lat:51.855783,lng:5.751205,kind:"restaurant",knownOperationalLocation:true,road:"A73",accessKm:112,source:"operator"}
];
export const median=(v:number[])=>{if(!v.length)return null;const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
export const haversineKm=(a:{lat:number;lng:number},b:{lat:number;lng:number})=>{const r=(n:number)=>n*Math.PI/180,dLat=r(b.lat-a.lat),dLng=r(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};

export function buildSegments(sites:MeasurementSite[]):Segment[]{const groups=new Map<string,MeasurementSite[]>();for(const s of sites){const from=Math.floor(s.km/SEGMENT_LENGTH_KM)*SEGMENT_LENGTH_KM,key=`${s.road}:${from}`,g=groups.get(key)??[];g.push(s);groups.set(key,g);}return[...groups.entries()].map(([key,g])=>{const[road,raw]=key.split(":"),kmFrom=Number(raw);return{road,kmFrom,kmTo:kmFrom+5,centerKm:kmFrom+2.5,lat:g.reduce((n,s)=>n+s.lat,0)/g.length,lng:g.reduce((n,s)=>n+s.lng,0)/g.length,sites:g};}).sort((a,b)=>a.road.localeCompare(b.road,"nl",{numeric:true})||a.kmFrom-b.kmFrom);}

const pressureFor=(speed:number|null,flow:number|null)=>{let sp=0,fp=0;if(speed!==null){if(speed<35)sp=38;else if(speed<50)sp=32;else if(speed<65)sp=25;else if(speed<80)sp=17;else if(speed<95)sp=8;}if(flow!==null){if(flow>=4500)fp=12;else if(flow>=3200)fp=9;else if(flow>=2200)fp=6;else if(flow>=1400)fp=3;}return{score:Math.min(50,sp+fp),congestionIndex:Math.min(100,Math.round(sp/38*75+fp/12*25))};};
export function sensorMetrics(seg:Segment,samples:Map<string,SiteTraffic>){const rows=seg.sites.map(site=>({site,sample:samples.get(site.id)})).filter((x):x is {site:MeasurementSite;sample:SiteTraffic}=>Boolean(x.sample)),speeds=rows.map(x=>x.sample.speedKph).filter((x):x is number=>x!==null&&x>0),flows=rows.map(x=>x.sample.flowVehiclesPerHour).filter((x):x is number=>x!==null),speed=median(speeds),flow=median(flows),byDirection=new Map<string,SiteTraffic[]>();for(const row of rows){const d=row.site.direction??"unknown",g=byDirection.get(d)??[];g.push(row.sample);byDirection.set(d,g);}const directionScores=[...byDirection.values()].map(group=>{const ds=group.map(x=>x.speedKph).filter((x):x is number=>x!==null&&x>0),df=group.map(x=>x.flowVehiclesPerHour).filter((x):x is number=>x!==null);return pressureFor(median(ds),median(df));}),base=directionScores.length?directionScores.sort((a,b)=>b.score-a.score)[0]:pressureFor(speed,flow);return{sensorCount:rows.length,directionCount:byDirection.size,averageSpeedKph:speed===null?null:Math.round(speed*10)/10,flowVehiclesPerHour:flow===null?null:Math.round(flow),congestionIndex:base.congestionIndex,score:base.score};}

export function segmentMatrix(signals:MatrixSignal[],seg:Segment){const relevant=signals.filter(s=>s.road===seg.road&&s.km!==null&&s.km>=seg.kmFrom&&s.km<seg.kmTo&&isActiveMatrix(s)),clusters=new Map<string,{p:number;low:boolean;closed:boolean}>();for(const s of relevant){const key=`${s.carriageway??"?"}:${Math.floor((s.km??0)*10)/10}`;let p=0,low=false,closed=false;if(s.display==="lane_closed"){p=7;closed=true;}else if(s.display==="lane_closed_ahead"){p=5;closed=true;}else if((s.speedLimit??999)<=50){p=4;low=true;}else if((s.speedLimit??999)<=70){p=3;low=true;}else if((s.speedLimit??999)<=90)p=1;const old=clusters.get(key);if(!old||p>old.p)clusters.set(key,{p,low,closed});}const v=[...clusters.values()];return{score:Math.min(22,v.reduce((n,x)=>n+x.p,0)),clusters:v.length,lowSpeed:v.filter(x=>x.low).length,closures:v.filter(x=>x.closed).length};}
const eventImpact=(e:TrafficEvent,d:number)=>{const b=e.kind==="accident"?11:e.kind==="closure"?10:e.kind==="obstruction"?6:e.kind==="traffic"?Math.min(10,5+Math.max(0,(e.queueLengthMeters??0)/1000)):e.kind==="weather"?4:2;return b*Math.max(.2,1-d/(MAX_EVENT_DISTANCE_KM+1));};
export function segmentEvents(seg:Segment,events:TrafficEvent[]){const items=events.map(e=>({event:e,distance:haversineKm(seg,e)})).filter(x=>x.distance<=MAX_EVENT_DISTANCE_KM&&(x.event.roadRef===seg.road||x.event.roadRef===null)),points=items.map(x=>eventImpact(x.event,x.distance)*(x.event.roadRef===seg.road?1:.45)).sort((a,b)=>b-a).slice(0,3);return{items,score:Math.min(18,points.reduce((a,b)=>a+b,0)),accidents:items.filter(x=>x.event.kind==="accident").length,obstructions:items.filter(x=>x.event.kind==="obstruction"||x.event.kind==="closure").length};}
export const weatherScore=(w:WeatherSnapshot|null)=>{if(!w)return 0;let s=0;if(w.precipitation>=2)s+=4;else if(w.precipitation>=.2)s+=2;if(w.windGusts>=70)s+=3;else if(w.windGusts>=50)s+=1;if(w.visibility>0&&w.visibility<2000)s+=3;else if(w.visibility>0&&w.visibility<5000)s+=1;return Math.min(6,s);};

const centroid=(geometry:{coordinates?:unknown}|undefined)=>{const pts:Array<[number,number]>=[];const walk=(v:unknown)=>{if(!Array.isArray(v))return;if(v.length>=2&&typeof v[0]==="number"&&typeof v[1]==="number"){pts.push([v[0],v[1]]);return;}v.forEach(walk);};walk(geometry?.coordinates);if(!pts.length)return null;const lng=pts.reduce((n,p)=>n+p[0],0)/pts.length,lat=pts.reduce((n,p)=>n+p[1],0)/pts.length;return lat>=51.15&&lat<=52.3&&lng>=4.2&&lng<=6.55?{lat,lng}:null;};
const featureName=(p:Record<string,unknown>)=>{for(const k of Object.keys(p).filter(k=>/naam|name|object|verzorg/i.test(k))){const v=p[k];if(typeof v==="string"&&v.trim().length>=2&&v.trim().length<=80)return v.trim();}return"RWS verzorgingsplaats";};
export function parseRwsRestAreas(text:string,points:RoadMetringPoint[]):CandidateLocation[]{try{const j=JSON.parse(text)as{features?:Array<{geometry?:{coordinates?:unknown};properties?:Record<string,unknown>}>},out:CandidateLocation[]=[];for(const[i,f]of(j.features??[]).entries()){const c=centroid(f.geometry);if(!c)continue;const nearest=points.map(point=>({point,d:haversineKm(c,point)})).filter(x=>x.d<=1.2).sort((a,b)=>a.d-b.d)[0];if(!nearest)continue;out.push({id:`rws-${nearest.point.road}-${nearest.point.km.toFixed(1)}-${i}`,name:featureName(f.properties??{}),address:`${nearest.point.road} km ${nearest.point.km.toFixed(1)} · officiële RWS-verzorgingsplaats`,lat:c.lat,lng:c.lng,kind:"service_area",knownOperationalLocation:false,road:nearest.point.road,accessKm:nearest.point.km,source:"rws"});}return out;}catch{return[];}}
export function findStandby(seg:Segment,locs:CandidateLocation[]){return locs.filter(l=>l.road===seg.road&&Math.abs(l.accessKm-seg.centerKm)<=MAX_STANDBY_ROAD_DISTANCE_KM).map(location=>({location,d:Math.abs(location.accessKm-seg.centerKm)})).sort((a,b)=>(a.d-(a.location.knownOperationalLocation?1.5:0))-(b.d-(b.location.knownOperationalLocation?1.5:0)))[0]??null;}