import type { MatrixRoadSummary, TrafficEvent, TrafficKind } from "@/lib/types";

export const TARGET_ROADS = new Set(["A1","A2","A12","A15","A16","A17","A18","A27","A28","A30","A50","A58","A59","A65","A67","A73","A325"]);
const REGION = { minLat: 51.15, maxLat: 52.30, minLng: 4.20, maxLng: 6.55 };

export type MatrixSignal = { signId:string; road:string|null; carriageway:string|null; lane:number|null; km:number|null; display:"speed"|"lane_closed"|"lane_closed_ahead"|"lane_open"|"restriction_end"|"blank"|"unknown"; speedLimit:number|null };
export type MeasurementSite = { id:string; name:string; road:string; km:number; lat:number; lng:number; speedIndexes:Set<number>; flowIndexes:Set<number> };
export type SiteTraffic = { siteId:string; measuredAt:string; speedKph:number|null; flowVehiclesPerHour:number|null };

const decode = (s:string) => s.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'");
export const stripTags = (s:string) => decode(s.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim());
export const tagValue = (xml:string, tag:string) => new RegExp(`<(?:(?:[A-Za-z0-9_-]+):)?${tag}\\b[^>]*>([\\s\\S]*?)<\\/(?:(?:[A-Za-z0-9_-]+):)?${tag}>`,"i").exec(xml)?.[1] ?? null;
const hasTag = (xml:string, tag:string) => new RegExp(`<(?:(?:[A-Za-z0-9_-]+):)?${tag}\\b`,"i").test(xml);
const attr = (s:string,name:string) => new RegExp(`(?:^|\\s)${name}="([^"]+)"`,"i").exec(s)?.[1] ?? null;
const numberTag = (xml:string,tag:string) => { const raw=tagValue(xml,tag); if(raw===null)return null; const n=Number(stripTags(raw).replace(",",".")); return Number.isFinite(n)?n:null; };
const median = (v:number[]) => { if(!v.length)return null; const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2); return a.length%2?a[m]:(a[m-1]+a[m])/2; };
const round1=(n:number)=>Math.round(n*10)/10;
const inRegion=(lat:number,lng:number)=>lat>=REGION.minLat&&lat<=REGION.maxLat&&lng>=REGION.minLng&&lng<=REGION.maxLng;
const coordinates=(body:string)=>{const src=tagValue(body,"coordinatesForDisplay")??tagValue(body,"locationForDisplay")??tagValue(body,"pointCoordinates")??body;const lat=numberTag(src,"latitude"),lng=numberTag(src,"longitude");return lat!==null&&lng!==null&&inRegion(lat,lng)?{lat,lng}:null;};
const roadRef=(body:string)=>{for(const t of ["roadNumber","roadName","roadNameAtOrigin","roadNameAtDestination"]){const raw=tagValue(body,t);if(!raw)continue;const m=/\b(?:A|N)\s?\d{1,3}\b/i.exec(stripTags(raw));if(m)return m[0].replace(/\s/g,"").toUpperCase();}return null;};
const sourceName=(body:string)=>{const src=tagValue(body,"source"),v=src?tagValue(src,"value"):null;return v?stripTags(v).slice(0,80):null;};

const classify=(type:string,body:string):TrafficKind|null=>{const v=type.toLowerCase();if(v.includes("abnormaltraffic"))return"traffic";if(v.includes("accident"))return"accident";if(v.includes("vehicleobstruction")||v.includes("generalobstruction")||v.includes("animalpresence"))return"obstruction";if(v.includes("maintenanceworks")||v.includes("constructionworks"))return"works";if(v.includes("poorenvironment")||v.includes("weatherrelatedroad"))return"weather";if(v.includes("roadorcarriagewayorlanemanagement")&&/closed|closure|blocked|laneClos|roadClos/i.test(body))return"closure";return null;};
const title=(kind:TrafficKind,body:string)=>{if(kind==="traffic"){const t=stripTags(tagValue(body,"abnormalTrafficType")??"");if(t==="stationaryTraffic")return"Stilstaand verkeer";if(t==="queuingTraffic")return"File";if(t==="slowTraffic")return"Langzaam verkeer";return"Afwijkend verkeersbeeld";}if(kind==="accident")return"Ongeval";if(kind==="obstruction")return"Obstakel / voertuig op de weg";if(kind==="closure")return"Afsluiting / rijstrookbeperking";if(kind==="works")return"Wegwerkzaamheden";return"Weers- of wegdekbelemmering";};
const fresh=(kind:TrafficKind,s:string|null)=>{if(!s)return kind==="works"||kind==="closure";const t=Date.parse(s);if(!Number.isFinite(t))return false;const age=Math.max(0,(Date.now()-t)/60000);return age<=(kind==="works"||kind==="closure"?1440:180);};

export function parseEvents(xml:string):TrafficEvent[]{const out:TrafficEvent[]=[];const rx=/<(?:(?:[A-Za-z0-9_-]+):)?situationRecord\b([^>]*)>([\s\S]*?)<\/(?:(?:[A-Za-z0-9_-]+):)?situationRecord>/gi;let m:RegExpExecArray|null;while((m=rx.exec(xml))){const attrs=m[1],body=m[2],raw=attr(attrs,"xsi:type")??attr(attrs,"type")??"SituationRecord",type=raw.split(":").pop()??raw,kind=classify(type,body),c=coordinates(body);if(!kind||!c)continue;const u=tagValue(body,"situationRecordVersionTime")??tagValue(body,"situationRecordCreationTime"),updatedAt=u?stripTags(u):null;if(!fresh(kind,updatedAt))continue;out.push({id:attr(attrs,"id")??`ndw-${out.length+1}`,kind,title:title(kind,body),type,lat:c.lat,lng:c.lng,roadRef:roadRef(body),queueLengthMeters:numberTag(body,"queueLength"),source:sourceName(body)??"NDW",updatedAt});}return out.slice(0,500);}

export function parseMatrix(xml:string):MatrixSignal[]{const map=new Map<string,MatrixSignal>();const rx=/<(?:(?:[A-Za-z0-9_-]+):)?event\b([^>]*)>([\s\S]*?)<\/(?:(?:[A-Za-z0-9_-]+):)?event>/gi;let m:RegExpExecArray|null;while((m=rx.exec(xml))){const attrs=m[1],body=m[2],id=stripTags(tagValue(body,"sign_id")??attr(attrs,"sign_id")??"");if(!id)continue;const x=map.get(id)??{signId:id,road:null,carriageway:null,lane:null,km:null,display:"unknown" as const,speedLimit:null};const r=tagValue(body,"road"),cw=tagValue(body,"carriageway");if(r)x.road=stripTags(r).replace(/\s/g,"").toUpperCase();if(cw)x.carriageway=stripTags(cw);x.lane=numberTag(body,"lane")??x.lane;x.km=numberTag(body,"km")??x.km;const speed=numberTag(body,"speedlimit");if(speed!==null){x.display="speed";x.speedLimit=speed;}else if(hasTag(body,"lane_closed_ahead"))x.display="lane_closed_ahead";else if(hasTag(body,"lane_closed"))x.display="lane_closed";else if(hasTag(body,"lane_open"))x.display="lane_open";else if(hasTag(body,"restriction_end"))x.display="restriction_end";else if(hasTag(body,"blank"))x.display="blank";map.set(id,x);}return[...map.values()].filter(x=>TARGET_ROADS.has(x.road??""));}

export function parseMeasurementSites(xml:string):MeasurementSite[]{const out:MeasurementSite[]=[];const rx=/<(?:(?:[A-Za-z0-9_-]+):)?measurementSite(?:Record)?\b([^>]*)>([\s\S]*?)<\/(?:(?:[A-Za-z0-9_-]+):)?measurementSite(?:Record)?>/gi;let m:RegExpExecArray|null;while((m=rx.exec(xml))){const id=attr(m[1],"id"),body=m[2];if(!id)continue;const name=stripTags(tagValue(body,"measurementSiteName")??""),loc=tagValue(body,"measurementSiteLocation")??body,rn=roadRef(loc),rm=/\bA\s?\d{1,3}\b/i.exec(name)?.[0].replace(/\s/g,"").toUpperCase()??null,road=rn??rm;if(!road||!TARGET_ROADS.has(road))continue;const kmMatch=/\b(?:km|hmp)\s*(\d{1,3}(?:[.,]\d{1,3})?)/i.exec(name),km=kmMatch?Number(kmMatch[1].replace(",",".")):NaN,c=coordinates(loc);if(!Number.isFinite(km)||!c)continue;const speedIndexes=new Set<number>(),flowIndexes=new Set<number>(),crx=/<(?:(?:[A-Za-z0-9_-]+):)?measurementSpecificCharacteristics\b([^>]*)>([\s\S]*?)<\/(?:(?:[A-Za-z0-9_-]+):)?measurementSpecificCharacteristics>/gi;let q:RegExpExecArray|null;while((q=crx.exec(body))){const idx=Number(attr(q[1],"index"));if(!Number.isInteger(idx))continue;const anyVehicle=!hasTag(q[2],"specificVehicleCharacteristics")||/<(?:(?:[A-Za-z0-9_-]+):)?vehicleType\b[^>]*>\s*anyVehicle\s*<\//i.test(q[2]);if(!anyVehicle)continue;const t=stripTags(tagValue(q[2],"specificMeasurementValueType")??"");if(t==="trafficSpeed")speedIndexes.add(idx);if(t==="trafficFlow")flowIndexes.add(idx);}if(speedIndexes.size||flowIndexes.size)out.push({id,name,road,km,lat:c.lat,lng:c.lng,speedIndexes,flowIndexes});}return out;}

export function parseTrafficSamples(xml:string,siteMap:Map<string,MeasurementSite>):SiteTraffic[]{const out:SiteTraffic[]=[];const rx=/<(?:(?:[A-Za-z0-9_-]+):)?siteMeasurements\b[^>]*>([\s\S]*?)<\/(?:(?:[A-Za-z0-9_-]+):)?siteMeasurements>/gi;let m:RegExpExecArray|null;while((m=rx.exec(xml))){const body=m[1],ref=/<(?:(?:[A-Za-z0-9_-]+):)?measurementSiteReference\b([^>]*)\/?\s*>/i.exec(body),id=ref?attr(ref[1],"id"):null;if(!id)continue;const cfg=siteMap.get(id);if(!cfg)continue;const mt=tagValue(body,"measurementTimeDefault")??"",measuredAt=stripTags(tagValue(mt,"timeValue")??mt),tm=Date.parse(measuredAt);if(!Number.isFinite(tm)||Math.abs(Date.now()-tm)>240000)continue;const speeds:number[]=[],flows:number[]=[],qrx=/<(?:(?:[A-Za-z0-9_-]+):)?(?:physicalQuantity|measuredValue)\b([^>]*)>([\s\S]*?)<\/(?:(?:[A-Za-z0-9_-]+):)?(?:physicalQuantity|measuredValue)>/gi;let q:RegExpExecArray|null;while((q=qrx.exec(body))){const idx=Number(attr(q[1],"index")),b=q[2];if(!Number.isInteger(idx)||/dataError[^>]*>\s*true\s*</i.test(b))continue;if(cfg.speedIndexes.has(idx)){const s=numberTag(b,"speed");if(s!==null&&s>=0&&s<=200&&s!==256)speeds.push(s);}if(cfg.flowIndexes.has(idx)){const f=numberTag(b,"vehicleFlowRate");if(f!==null&&f>=0&&f<=10000)flows.push(f);}}let speed=median(speeds);const flow=flows.length?flows.reduce((a,b)=>a+b,0):null;if(speeds.length&&flows.length===speeds.length){const total=flows.reduce((a,b)=>a+b,0);if(total>0)speed=speeds.reduce((sum,s,i)=>sum+s*flows[i],0)/total;}if(speed!==null||flow!==null)out.push({siteId:id,measuredAt,speedKph:speed===null?null:round1(speed),flowVehiclesPerHour:flow});}return out;}

export const isActiveMatrix=(s:MatrixSignal)=>s.display==="lane_closed"||s.display==="lane_closed_ahead"||(s.display==="speed"&&(s.speedLimit??999)<=90);
export function matrixSummary(signals:MatrixSignal[]):MatrixRoadSummary[]{const map=new Map<string,MatrixRoadSummary>();for(const s of signals.filter(isActiveMatrix)){if(!s.road)continue;const x=map.get(s.road)??{road:s.road,active:0,closures:0,lowSpeed:0};x.active++;if(s.display==="lane_closed"||s.display==="lane_closed_ahead")x.closures++;if(s.display==="speed"&&(s.speedLimit??999)<=70)x.lowSpeed++;map.set(s.road,x);}return[...map.values()].sort((a,b)=>b.closures-a.closures||b.lowSpeed-a.lowSpeed||b.active-a.active).slice(0,30);}